import os
import sys
import shutil
from flask import Flask, render_template, request ,flash
import webbrowser
import threading
import socket


app = Flask(__name__, static_folder='static', template_folder='templates')



def get_resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except AttributeError:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

BUNDLED_STATIC_DIR = get_resource_path("static") # Path to the bundled static folder

# path to the icon file inside the "style" folder
ICON_PATH = get_resource_path("style/style_icon.ico")





# Define routes
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/new_project')  # When press on New Project in the index
def new_project():
    return render_template('new_project.html')

@app.route('/open_project')  # When press on Open Project in the index
def open_project():
    return render_template('open_project.html')










# --- Helper: Load Data from file_configuration ---
def load_project_data(file_config_path):
    file_map = {
        'Electrostatic.dat': [],
        'External_Field.dat': [],
        'Ferro_Geometry.dat': [],
        'Gradient_Field.dat': [],
        'Initial_Polarization.dat': [],
        'Landau_Free.dat': []
    }

    for filename in file_map:
        full_path = os.path.join(file_config_path, filename)
        if not os.path.exists(full_path):
            raise FileNotFoundError(f"Missing file: {filename}")
        with open(full_path, 'r') as f:
            for line in f:
                line = line.strip()  # Remove leading/trailing whitespace
                
                # If the line starts with "----", stop processing this file
                if line.startswith("----"):
                    break  # Exit the inner loop (processing lines of the current file)

                # Skip empty or comment lines
                if not line or line.startswith('//') or line.startswith('!'):
                    continue

                # Split the line by spaces and take the first element
                words = line.split()
                if words:  # Ensure the line is not just spaces after stripping
                    first_word = words[0]
                    try:
                        file_map[filename].append(float(first_word))
                    except ValueError:
                        file_map[filename].append(first_word)  # Keep as string if not a float
                    except TypeError as e:
                        print(f"TypeError processing line: '{line}' in {filename}: {e}")
                    except Exception as e:
                        print(f"An unexpected error occurred while processing line: '{line}' in {filename}: {e}")

    return (
        file_map['Electrostatic.dat'],
        file_map['External_Field.dat'],
        file_map['Ferro_Geometry.dat'],
        file_map['Gradient_Field.dat'],
        file_map['Initial_Polarization.dat'],
        file_map['Landau_Free.dat']
    )







# --- Helper: Rewrite data to the files ---
def update_project_data(moode , file_path , values):

    if moode == "Ferro_Geometry":
        title = "//Geometry Parameters"
        comment=["!Ncx (int)","!Ncy (int)","!Ncz (int)","!FLAG_SHAPE 1 quadr o rett, 2 file, 3 cerchio o ell(int)","!nome file da legg o scrivere","!delta_x(m) (double)","!delta_y(m) (double)","!delta_z(m) (double)",'!h (in units of delta)','!duration time','!step size','!FLAG_INTEGRATOR 0(No integrator) 1(HEUN)  2(RK45 fixed)  3(RK45 adaptive) 4(AB3M2 fixed) 5(AB3M2 Adaptive) ','!start_adapting (number of steps after adaptive time stepping will start)','!FLAG_LANDAU_ENERGY 0 (Not calculating) 1 (calculating)','!Error_tolerance for RK45 and AB3M2 methods','!max_dt (how many times the step size can increase than initial step size in RK45 or AB3M2)','!min_dt (how many times the step size can decrease than initial step size in RK45 or AB3M2)']
        text_comment="\n\n\n----COMMENT----\nFLAG_SHAPE\n1 --> the shape constant is rectangular or square, the file is 	automatically generated by the software;\n2 --> the shape is read from file (1 col (int)with dimension NCx*Ncy*Ncz);\n3 --> the shape is elliptical or circular, the file is 	automatically generated by the software;\n\n\n----ENDCOMMENT----\n\n\n----NOTE----\n\n\n\n----ENDNOTE----\n"

    elif moode == "Initial_Polarization":
        title ="//Pinicial"
        comment=["!FLAG_PINICIAL 1, 2, 3","!pol_x (Cm-2) uniform","!pol_y (Cm-2) uniform","!pol_z (Cm-2) uniform","!nome del file","!nome del file"]
        text_comment="\n\n\n----COMMENT----\nFLAG_PINICIAL\n1 --> initial polarization is uniform;\n2 --> initial polarization is non_uniform along Z-axis taken from file;\n3 --> initial polarization is entirely non_uniform taken from file;\n\n----ENDCOMMENT----\n\n----NOTE----\n\n----ENDNOTE----\n"

    elif moode == "Landau_Free_Field_Parameters":
        title = "//Landau Free parameters"
        comment=['!FLAG_LANDAU  0, 1 (int)','!FLAG_NOISE  0, 1, 2','!FLAG_ALPHA0  1, 2, 3 (int)','!(C-1m2N) alpha0_constant','!nome del file','!nome del file','!FLAG_ALPHA2  1, 2, 3 (int)','!(C-4m6N) alpha2_constant','!nome del file','!nome del file','!FLAG_ALPHA3  1, 2, 3 (int)','!(C-4m6N) alpha3_constant','!nome del file','!nome del file','!FLAG_ALPHA4  1, 2, 3 (int)','!(C-6m10N) alpha4_constant','!nome del file','!nome del file','!FLAG_ALPHA5  1, 2, 3 (int)','!(C-6m10N) alpha5_constant','!nome del file','!nome del file','!FLAG_ALPHA6  1, 2, 3 (int)','!(C-6m10N) alpha6_constant','!nome del file','!nome del file','!(C/m2) reference_polarization_x','!(C/m2) reference_polarization_y','!(C/m2) reference_polarization_z','!(C-2m2N) alpha1_reference constant to normalize','!FLAG_SUSCIPTIBILITY_WEIGHTS   1, 2, 3 (int)','!susiptibilityWeight value','!nome del file','!nome del file','!FLAG_TEMPERATURE  1, 2, 3 (int)','!(K) temperature value','!nome del file','!nome del file','!FLAG_TRANSITION_TEMP  1, 2, 3 (int)','!(K) transition temperature  value','!nome del file','!nome del file','!FLAG_RELAXATION  1, 2, 3 (int)','!(s-1m-2C2N-1) relaxation coefficient  value','!nome del file','!nome del file','!(s-1m-2C2N-1) reference relaxation coefficient']
        text_comment ="\n\n\n----COMMENT----\nCurrently only Flag 1 is working.\nFLAG_LANDAU\n0 -->	 Landau free field not calculated;\n1 -->    Landau free field calculated;\nFLAG_NOISE\n0 -->	 Random noise is not included;\n1 -->    Random noise is included;\nFLAG_ALPHA0\n1 -->	 alpha0 has a single constant value;\n2 -->    alpha0 change values along z_layer, input from file;\n3 -->    alpha0 has entirely non_uniform values, input from file;\nFLAG_ALPHA2\n1 -->	 alpha2 has a single constant value;\n2 -->    alpha2 change values along z_layer, input from file;\n3 -->    alpha2 has entirely non_uniform values, input from file;\nFLAG_ALPHA3\n1 -->	 alpha3 has a single constant value;\n2 -->    alpha3 change values along z_layer, input from file;\n3 -->    alpha3 has entirely non_uniform values, input from file;\nFLAG_ALPHA4\n1 -->	 alpha4 has a single constant value;\n2 -->    alpha4 change values along z_layer, input from file;\n3 -->    alpha4 has entirely non_uniform values, input from file;\nFLAG_ALPHA5\n1 -->	 alpha5 has a single constant value;\n2 -->    alpha5 change values along z_layer, input from file;\n3 -->    alpha5 has entirely non_uniform values, input from file;\nFLAG_ALPHA6\n1 -->	 alpha6 has a single constant value;\n2 -->    alpha6 change values along z_layer, input from file;\n3 -->    alpha6 has entirely non_uniform values input from file;\nFLAG_TEPERATURE\n1 -->	 temperature has a single constant value;\n2 -->    temperature change values along z_layer, input from file;\n3 -->    temperature has entirely non_uniform values input from file;\nFLAG_RELAXATION\n1 -->	 coefficient related to domain wall mobolity has a single constant value;\n2 -->    coefficient related to domain wall mobolity has a change values along z_layer, input from file;\n3 -->    coefficient related to domain wall mobolity has a has entirely non_uniform values input from file;\n\n\n\n\n\n----ENDCOMMENT----\n\n"


    elif moode == 'Gradient_Field_Parameters':
        title = '//Gradient field parameters'
        comment = ['!FLAG_GRADIENT  0, 1 (int)','!(m4NC-2) G0_constant','!FLAG_G1  1, 2, 3 (int)','!(m4NC-2) G1_constant','!nome del file','!nome del file','!FLAG_G2  1, 2, 3 (int)','!(m4NC-2) G2_constant','!nome del file','!nome del file','!FLAG_G3  1, 2, 3 (int)','!(m4NC-2) G3_constant','!nome del file','!nome del file','!FLAG_G4  1, 2, 3 (int)','!(m4NC-2) G4_constant','!nome del file','!nome del file','!FLAG_BC	0, 1, 2 (int)']
        text_comment="\n\n\n----COMMENT----\nFLAG_G0\n1 -->	 G0 has a single constant value;\n2 -->    G0 change values along z_layer, input from file;\n3 -->    G0 has entirely non_uniform values, input from file;\nFLAG_G1\n1 -->	 G1 has a single constant value;\n2 -->    G1 change values along z_layer, input from file;\n3 -->    G1 has entirely non_uniform values, input from file;\nFLAG_G2  \n1 -->	 G2 has a single constant value;\n2 -->    G2 change values along z_layer, input from file;\n3 -->    G2 has entirely non_uniform values, input from file;\nFLAG_G3  \n1 -->	 G3 has a single constant value;\n2 -->    G3 change values along z_layer, input from file;\n3 -->    G3 has entirely non_uniform values, input from file;\nFLAG_G4  \n1 -->	 G4 has a single constant value;\n2 -->    G4 change values along z_layer, input from file;\n3 -->    G4 has entirely non_uniform values, input from file;\nFLAG_BC  \n0 -->	 simple boundary conditions (Neumann type boundary conditions with 0 flux);\n1 -->    open boundary conditions (Drichlet type boundary conditions with 0 value on boundary);\n2 -->    periodic boundary conditions;\n\n\n\n\n\n\n\n----ENDCOMMENT----\n\n\n"

    elif moode == "External_Field":
        title = "//Field external"
        comment = ['!FLAG_FIELD 0 (No Field), 1(const), 2(z_variable), 3 (non_uniform) (int)','!FLAG_INPUT_TYPE 1(Spherical), 2(cartesian)','!field ext (V/m)','!H_theta','!H_phi','!H_x','!H_y','!H_z','!nome file','!nome file','! FLAG_FIELD_AC 0 (No AC Field), 1(const), 2(z_variable), 3(non_uniform)','! hx (V/m)','! hy (V/m)','! hz (V/m)','!nome file','!nome file','!FLAG_FREQUENCY 1(const), 2(z_variable), 3(non_uniform)','!frequency','!nome file','!nome file','!FLAG_PHASE 1(const), 2(z_variable), 3(non_uniform)','! fi_x','! fi_y','! fi_z','!nome file','!nome file','!FLAG_FIELD_PULSE 0(no), 1(si)','!nfield (int)','!nome file di due colonne','!H_theta_pulse','!H_phi_pulse']
        text_comment="\n\n\n----COMMENT----\nFLAG_FIELD \n0 --> field extern not computed;\n1 --> field external is constant input value directly (mT); 	\n2 --> field extern is variable along z direction input from file;\n3 --> field extern is entirely non uniform input from file;\n\n\n\n----ENDCOMMENT----\n\n\n----NOTE----\n\n\n\n----ENDNOTE----\n"

    elif moode == "Electrostatic_Field_Parameters":
        title = "//Configuration file for electrostatic field"
        comment = ['!FLAG_TENSOR','!Dx','!Dy','!Dz','!FLAG_PADDING','!Pad_cx','!Pad_cy','!Pad_cz']
        text_comment = "\n\n\n----COMMENT----\nFLAG_TENSOR\n0 --> magnetostatic field = 0;\n1 --> Demag Tensor computed in CPU (long double);\n2 --> Demag Tensor computed in GPU (double);\n3 --> THIN-FILM approximation \n	Hx=-Dx*mx, Hy = - Dy*my, Hz = -Dz*mz\n	the values are computed for each computational cell\n	Ms non uniform is not supported for FLAG_TENSOR = 3;\nFLAG_PADDING\n0 --> Software computation (init());\n1 --> Manual computation \n	Mcx = Ncx + Pad_cx\n	Mcy = Ncy + Pad_cy\n	Mcz = Ncz + Pad_cz\n\n----ENDCOMMENT----\n\n\n----NOTE----\nBisogna testare FLAG_TENSOR=0;\nBisogna testare FLAG_TENSOR=3;\nPer FLAG_TENSOR=2 bisogna riprodurre i problemi standard #4 e #5; \nBisogna testare FLAG_TENSOR 1 e 2 con FLAG_PADDING =1 considerando la somma di Mcx, Mcy e Mcz dispari;\n\n----ENDNOTE----\n"
    else:
        print('Error')

    
    # Write values to the file
    with open(file_path, 'w') as file:
        file.write(f"{title}\n")
        for i, value in enumerate(values):
            file.write(f"{value}\t\t\t")
            file.write(f"{comment[i]}\n")
        file.write(f"{text_comment}")











# --- Route: New Project Submit ---
@app.route('/new_project_submit', methods=['POST'])
def new_project_submit():
    project_folder = request.form.get('P_Folder')
    print(f"Project Folder Value: {project_folder}")

    if project_folder:
        new_project_path = os.path.join('/path/to/your/projects', project_folder)
        file_config_path = os.path.join(new_project_path, 'file_configuration')

        try:
            os.makedirs(file_config_path, exist_ok=True)
            print(f"Created: {file_config_path}")

            if os.path.exists(BUNDLED_STATIC_DIR):
                for file_name in os.listdir(BUNDLED_STATIC_DIR):
                    if file_name.endswith(".dat"):
                        src = os.path.join(BUNDLED_STATIC_DIR, file_name)
                        dst = os.path.join(file_config_path, file_name)
                        shutil.copy2(src, dst)
                        print(f"Copied {file_name} to {file_config_path}")
            else:
                return render_template('new_project.html', error="Static source folder not found.")

            # Load project data from file_configuration
            data_lists = load_project_data(file_config_path)

            return render_template('main_page.html',project_path=new_project_path, message=f"Project '{project_folder}' created.",
                                   List_Electrostatic=data_lists[0],
                                   List_External_Field=data_lists[1],
                                   List_Ferro_Geometry=data_lists[2],
                                   List_Gradient_Field=data_lists[3],
                                   List_Initial_Polarization=data_lists[4],
                                   List_Landau_Free=data_lists[5])

        except Exception as e:
            print(f"Error: {e}")
            return render_template('new_project.html', error=f"Failed to create project: {e}")
    else:
        return render_template('new_project.html', error="Project folder name is required.")










# --- Route: Open Project Submit ---
@app.route('/open_project_submit', methods=['POST']) 
def open_project_submit():
    project_location = request.form.get('P_Folder')
    print(f"Opening project at: {project_location}")

    if not project_location:
        return render_template('open_project.html', error="Please provide a project location.")

    file_config_path = os.path.join(project_location, 'file_configuration')
    REQUIRED_PROJECT_FILES = ["Electrostatic.dat", "External_Field.dat", "Ferro_Geometry.dat",
                              "Gradient_Field.dat", "Initial_Polarization.dat", "Landau_Free.dat"]

    missing_files = [f for f in REQUIRED_PROJECT_FILES if not os.path.isfile(os.path.join(file_config_path, f))]

    if missing_files:
        return render_template('open_project.html',
                               error=f"Missing files in 'file_configuration': {', '.join(missing_files)}")

    try:
        data_lists = load_project_data(file_config_path)

        return render_template('main_page.html',project_path=project_location,
                               message=f"Project opened from '{project_location}'.",
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5])
    except Exception as e:
        print(f"Load error: {e}")
        return render_template('open_project.html', error=f"Failed to load project data: {e}")











# --- Route: Submit Configuration of Ferro_Geometry Form
@app.route('/Ferro_Geometry', methods=['POST'])
def Ferro_Geometry():
    try:
        # Extract all relevant form fields
        fields = ["Ncx",
                  "Ncy",
                  "Ncz",
                  "FLAG_SHAPE",
                  "shape_file_input",
                  "delta_x",
                  "delta_y",
                  "delta_z",
                  "h_param",
                  "duration_time",
                  "step_size",
                  "FLAG_INTEGRATOR",
                  "start_adapting",
                  "FLAG_LANDAU_ENERGY",
                  "Error_tolerance",
                  "max_dt",
                  "min_dt"]
        
        values = [request.form.get(field, '0') for field in fields]

        # Determine file path
        project_path = request.form.get('project_path')
        config_path = os.path.join(project_path, 'file_configuration')
        file_path = os.path.join(config_path, 'Ferro_Geometry.dat')

        # Insert the file name if uploaded and save it
        index_number_temp = [4]  # Only the shape_file_input
        for x in index_number_temp:
            temp = request.files.get(fields[x])
            if temp and temp.filename:
                values[x] = temp.filename
                destination_path = os.path.join(project_path, temp.filename)
                temp.save(destination_path)
            else:
                values[x] = 'None'

        # Write values to the file
        moode = "Ferro_Geometry"
        update_project_data(moode , file_path , values)

        # Try to reload data
        try:
            data_lists = load_project_data(config_path)
            load_error = False
        except:
            data_lists = [[], [], [], [], [], []]
            load_error = True

        # Final message to user
        if load_error:
            message = "Ferro Geometry configuration saved, but failed to reload data. Displaying empty form."
        else:
            message = "Ferro Geometry configuration saved."

        return render_template('main_page.html',
                               message=message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5])

    except Exception as e:
        error_message = f"Error Saving Ferro Geometry configurations: {e}"
        print(error_message)

        # Optional: load empty or fallback data for rendering
        project_path = request.form.get('project_path', '')
        config_path = os.path.join(project_path, 'file_configuration')
        
        try:
            data_lists = load_project_data(config_path)
        except:
            data_lists = [[], [], [], [], [], []]  # fallback if loading fails

        return render_template('main_page.html',
                               message=error_message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5]), 500



















# --- Route: Submit Configuration of Initial_Polarization Form
@app.route('/Initial_Polarization', methods=['POST'])
def Initial_Polarization():
    try:
        # Extract all relevant form fields
        fields = ["FLAG_PINICIAL",
                  "pol_x",
                  "pol_y",
                  "pol_z_uniform",
                  "pinicial_z_file",
                  "pinicial_non_uniform_file"]

        values = [request.form.get(field, '0') for field in fields]

        # Determine file path
        project_path = request.form.get('project_path')
        config_path = os.path.join(project_path, 'file_configuration')
        file_path = os.path.join(config_path, 'Initial_Polarization.dat')

        # Handle file uploads
        index_number_temp = [4, 5]
        for x in index_number_temp:
            temp = request.files.get(fields[x])
            if temp and temp.filename:
                values[x] = temp.filename
                destination_path = os.path.join(project_path, temp.filename)
                temp.save(destination_path)
            else:
                values[x] = 'None'

        # Write values to the file
        moode = "Initial_Polarization"
        update_project_data(moode , file_path , values)

        # Try to reload data
        try:
            data_lists = load_project_data(config_path)
            load_error = False
        except:
            data_lists = [[], [], [], [], [], []]
            load_error = True

        # Final message
        if load_error:
            message = "Initial Polarization configuration saved, but failed to reload data. Displaying empty form."
        else:
            message = "Initial Polarization configuration saved."

        return render_template('main_page.html',
                               message=message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5])

    except Exception as e:
        error_message = f"Error saving Initial_Polarization config: {e}"
        print(error_message)

        # Optional: fallback data load
        project_path = request.form.get('project_path', '')
        config_path = os.path.join(project_path, 'file_configuration')

        try:
            data_lists = load_project_data(config_path)
        except:
            data_lists = [[], [], [], [], [], []]

        return render_template('main_page.html',
                               message=error_message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5]), 500













# --- Route: Submit Configuration of Landau_Free_Field_Parameters Form
@app.route('/Landau_Free_Field_Parameters', methods=['POST'])
def Landau_Free_Field_Parameters():
    try:
        # Extract all relevant form fields
        fields = ["FLAG_LANDAU",
                  "FLAG_NOISE",
                  "FLAG_ALPHA0",
                  "alpha0_constant",
                  "alpha0_z_file",
                  "alpha0_non_uniform_file",
                  "FLAG_ALPHA2",
                  "alpha2_constant",
                  "alpha2_z_file",
                  "alpha2_non_uniform_file",
                  "FLAG_ALPHA3",
                  "alpha3_constant",
                  "alpha3_z_file",
                  "alpha3_non_uniform_file",
                  "FLAG_ALPHA4",
                  "alpha4_constant",
                  "alpha4_z_file",
                  "alpha4_non_uniform_file",
                  "FLAG_ALPHA5",
                  "alpha5_constant",
                  "alpha5_z_file",
                  "alpha5_non_uniform_file",
                  "FLAG_ALPHA6",
                  "alpha6_constant",
                  "alpha6_z_file",
                  "alpha6_non_uniform_file",
                  "reference_polarization_x",
                  "reference_polarization_y",
                  "reference_polarization_z",
                  "alpha1_reference",
                  "FLAG_SUSCIPTIBILITY_WEIGHTS",
                  "susiptibilityWeight",
                  "susciptibilityWeights_z_file",
                  "susciptibilityWeights_non_uniform_file",
                  "FLAG_TEMPERATURE",
                  "temperature",
                  "temperature_z_file",
                  "temperature_non_uniform_file",
                  "FLAG_TRANSITION_TEMP",
                  "transition_temperature",
                  "transitionTemp_z_file",
                  "transitionTemp_non_uniform_file",
                  "FLAG_RELAXATION",
                  "relaxation",
                  "relaxation_z_file",
                  "relaxation_non_uniform_file",
                  "reference_relaxation"]

        values = [request.form.get(field, '0') for field in fields]

        # Determine file path
        project_path = request.form.get('project_path')
        config_path = os.path.join(project_path, 'file_configuration')
        file_path = os.path.join(config_path, 'Landau_Free.dat')

        # Handle file uploads
        index_number_temp = [4, 5, 8, 9, 12, 13, 16, 17, 20, 21, 24, 25, 32, 33, 36, 37, 40, 41, 44, 45]
        for x in index_number_temp:
            temp = request.files.get(fields[x])
            if temp and temp.filename:
                values[x] = temp.filename
                destination_path = os.path.join(project_path, temp.filename)
                temp.save(destination_path)
            else:
                values[x] = 'None'

        # Write values to the file
        moode = "Landau_Free_Field_Parameters"
        update_project_data(moode , file_path , values)

        # Attempt to reload project data
        try:
            data_lists = load_project_data(config_path)
            load_error = False
        except:
            data_lists = [[], [], [], [], [], []]
            load_error = True

        message = "Landau Free Field Parameters configuration saved."
        if load_error:
            message += " However, failed to reload data. Displaying empty form."

        return render_template('main_page.html',
                               message=message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5])

    except Exception as e:
        error_message = f"Error saving Landau_Free_Field_Parameters config: {e}"
        print(error_message)

        # Optional fallback for rendering
        project_path = request.form.get('project_path', '')
        config_path = os.path.join(project_path, 'file_configuration')

        try:
            data_lists = load_project_data(config_path)
        except:
            data_lists = [[], [], [], [], [], []]

        return render_template('main_page.html',
                               message=error_message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5]), 500














# --- Route: Submit Configuration of Gradient_Field_Parameters Form
@app.route('/Gradient_Field_Parameters', methods=['POST'])
def Gradient_Field_Parameters():
    try:
        # Extract all relevant form fields
        fields = ["FLAG_GRADIENT",
                  "G0_constant",
                  "FLAG_G1",
                  "G1_constant",
                  "G1_z_file",
                  "G1_non_uniform_file",
                  "FLAG_G2",
                  "G2_constant",
                  "G2_z_file",
                  "G2_non_uniform_file",
                  "FLAG_G3",
                  "G3_constant",
                  "G3_z_file",
                  "G3_non_uniform_file",
                  "FLAG_G4",
                  "G4_constant",
                  "G4_z_file",
                  "G4_non_uniform_file",
                  "FLAG_BC"]
        
        values = [request.form.get(field, '0') for field in fields]

        # Determine file path
        project_path = request.form.get('project_path')
        config_path = os.path.join(project_path, 'file_configuration')
        file_path = os.path.join(config_path, 'Gradient_Field.dat')

        # Handle file uploads
        index_number_temp = [4, 5, 8, 9, 12, 13, 16, 17]
        for x in index_number_temp:
            temp = request.files.get(fields[x])
            if temp and temp.filename:
                values[x] = temp.filename
                destination_path = os.path.join(project_path, temp.filename)
                temp.save(destination_path)
            else:
                values[x] = 'None'

        # Write values to the file
        moode = "Gradient_Field_Parameters"
        update_project_data(moode , file_path , values)

        # Attempt to reload project data
        try:
            data_lists = load_project_data(config_path)
            load_error = False
        except:
            data_lists = [[], [], [], [], [], []]
            load_error = True

        message = "Gradient Field Parameters configuration saved."
        if load_error:
            message += " However, failed to reload data. Displaying empty form."

        return render_template('main_page.html',
                               message=message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5])

    except Exception as e:
        error_message = f"Error saving Gradient_Field_Parameters config: {e}"
        print(error_message)

        # Optional fallback for rendering
        project_path = request.form.get('project_path', '')
        config_path = os.path.join(project_path, 'file_configuration')

        try:
            data_lists = load_project_data(config_path)
        except:
            data_lists = [[], [], [], [], [], []]

        return render_template('main_page.html',
                               message=error_message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5]), 500















# --- Route: Submit Configuration of External_Field Form
@app.route('/External_Field', methods=['POST'])
def External_Field():
    try:
        # Extract all relevant form fields
        fields = ["flag_field",
                  "flag_input_type",
                  "field_ext_spherical",
                  "h_theta",
                  "h_phi",
                  "h_x",
                  "h_y",
                  "h_z",
                  "field_z_variable_file",
                  "field_non_uniform_file",
                  "flag_field_ac",
                  "hx_ac",
                  "hy_ac",
                  "hz_ac",
                  "ac_z_variable_file",
                  "ac_non_uniform_file",
                  "flag_frequency",
                  "constant_frequency_group",
                  "z_variable_frequency_group",
                  "non_uniform_frequency_group",
                  "flag_phase",
                  "fi_x",
                  "fi_y",
                  "fi_z",
                  "z_variable_phase_group",
                  "non_uniform_phase_group",
                  "flag_field_pulse",
                  "nfield",
                  "file_pulse",
                  "h_theta_pulse",
                  "h_phi_pulse"]
        
        values = [request.form.get(field, '0') for field in fields]

        # Determine file path
        project_path = request.form.get('project_path')
        config_path = os.path.join(project_path, 'file_configuration')
        file_path = os.path.join(config_path, 'External_Field.dat')

        # Handle file uploads
        index_number_temp = [8, 9, 14, 15, 18, 19, 24, 25, 28]
        for x in index_number_temp:
            temp = request.files.get(fields[x])
            if temp and temp.filename:
                values[x] = temp.filename  # Update the values list
                destination_path = os.path.join(project_path, temp.filename)
                temp.save(destination_path)
            else:
                values[x] = 'None'  # Keep the default if no file

        # Write values to the file
        moode = "External_Field"
        update_project_data(moode , file_path , values)

        # Attempt to reload project data
        try:
            data_lists = load_project_data(config_path)
            load_error = False
        except:
            data_lists = [[], [], [], [], [], []]
            load_error = True

        message = "External Field saved."
        if load_error:
            message += " However, failed to reload data. Displaying empty form."

        return render_template('main_page.html',
                               message=message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5])

    except Exception as e:
        error_message = f"Error saving External_Field config: {e}"
        print(error_message)

        # Optional fallback for rendering
        project_path = request.form.get('project_path', '')
        config_path = os.path.join(project_path, 'file_configuration')

        try:
            data_lists = load_project_data(config_path)
        except:
            data_lists = [[], [], [], [], [], []]

        return render_template('main_page.html',
                               message=error_message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5]), 500















# --- Route: Submit Configuration of Electrostatic_Field_Parameters Form
@app.route('/Electrostatic_Field_Parameters', methods=['POST'])
def electrostatic_field_parameters():
    try:
        # Extract all relevant form fields
        fields = ['FLAG_TENSOR',
                  'Dx',
                  'Dy',
                  'Dz',
                  'FLAG_PADDING',
                  'Pad_cx',
                  'Pad_cy',
                  'Pad_cz']
        values = [request.form.get(field, '0') for field in fields]

        # Determine file path
        project_path = request.form.get('project_path')
        config_path = os.path.join(project_path, 'file_configuration')
        file_path = os.path.join(config_path, 'Electrostatic.dat')

        # Handle file uploads (if any)
        index_number_temp = []
        for x in index_number_temp:
            temp = request.files.get(fields[x])
            if temp and temp.filename:
                values[x] = temp.filename  # Update the values list
                destination_path = os.path.join(project_path, temp.filename)
                temp.save(destination_path)
            else:
                values[x] = 'None'  # Keep the default if no file

        # Write values to the file
        moode = "Electrostatic_Field_Parameters"
        update_project_data(moode , file_path , values)

        # Attempt to reload project data
        try:
            data_lists = load_project_data(config_path)
            load_error = False
        except:
            data_lists = [[], [], [], [], [], []]
            load_error = True

        message = "Electrostatic configuration saved."
        if load_error:
            message += " However, failed to reload data. Displaying empty form."

        return render_template('main_page.html',
                               message=message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5])

    except Exception as e:
        error_message = f"Error saving electrostatic config: {e}"
        print(error_message)

        # Optional fallback for rendering
        project_path = request.form.get('project_path', '')
        config_path = os.path.join(project_path, 'file_configuration')

        try:
            data_lists = load_project_data(config_path)
        except:
            data_lists = [[], [], [], [], [], []]

        return render_template('main_page.html',
                               message=error_message,
                               project_path=project_path,
                               List_Electrostatic=data_lists[0],
                               List_External_Field=data_lists[1],
                               List_Ferro_Geometry=data_lists[2],
                               List_Gradient_Field=data_lists[3],
                               List_Initial_Polarization=data_lists[4],
                               List_Landau_Free=data_lists[5]), 500










# Function to open browser automatically
def open_browser():
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
    webbrowser.open_new(f'http://{local_ip}:5000/')  # Automatically opens the correct IP

if __name__ == "__main__":
    # Start the browser after a short delay
    threading.Timer(1.25, open_browser).start()
    # Run the app
    app.run(host="0.0.0.0", port=5000, debug=False)
